const traceTomato = [
  { farmerCode: "KR-041", harvestCluster: "Hosur cluster", contributedKg: 240, grade: "A", harvestedOn: "25 Aug 2026" },
  { farmerCode: "KR-079", harvestCluster: "Hosur cluster", contributedKg: 210, grade: "A", harvestedOn: "25 Aug 2026" },
  { farmerCode: "KR-116", harvestCluster: "Shoolagiri cluster", contributedKg: 170, grade: "A", harvestedOn: "24 Aug 2026" },
];

export const demoFallback: any = {
  dataNotice: "Mandi reference prices are dated public AGMARKNET/data.gov.in records. Farmers, FPOs, order quantities, routes, forecasts, and impact figures are clearly labelled illustrative demo records.",
  listings: [
    { id: "tomato-grade-a", crop: "Sun-ripened tomato", variety: "Market grade, sorted", category: "Fresh produce", grade: "Grade A", availableKg: 620, minOrderKg: 5, fpo: "Krishnagiri Harvest Collective", state: "Tamil Nadu", harvestWindow: "Packed within 18 hours", price: { directBuyerPrice: 28, farmerDirectEarnings: 20.5, fpoServices: 2.1, logistics: 3.4, qualityAndPacking: 2, conventionalBuyerPrice: 42, farmerConventionalEarnings: 13.4 }, marketReference: { pricePerKg: 22.5, market: "Katpadi Uzhavar Sandhai", state: "Tamil Nadu", observedOn: "26 Aug 2026", source: "AGMARKNET / data.gov.in, modal price" }, lotCode: "KHC-TOM-0826-A", verification: { status: "Demo verified", reference: "FPO-DEMO-26033-01", copy: "Illustrative FPO onboarding record; production verification would use consented organisation documents and field validation." }, traceability: traceTomato, demandSignal: "High demand", color: "tomato", comparison: { buyerSavings: 14, farmerUpliftPercent: 53, directFarmerSharePercent: 73 }, aggregation: { totalKg: 620, distinctFarmers: 3 } },
    { id: "red-onion", crop: "Red onion", variety: "Medium bulb, graded", category: "Fresh produce", grade: "Grade A", availableKg: 980, minOrderKg: 10, fpo: "Kaveri Pooled Produce FPO", state: "Tamil Nadu", harvestWindow: "Cured & traceable", price: { directBuyerPrice: 52, farmerDirectEarnings: 38, fpoServices: 3.5, logistics: 6.5, qualityAndPacking: 4, conventionalBuyerPrice: 68, farmerConventionalEarnings: 26 }, marketReference: { pricePerKg: 52.5, market: "Hosur Uzhavar Sandhai", state: "Tamil Nadu", observedOn: "26 Aug 2026", source: "AGMARKNET / data.gov.in, modal price" }, lotCode: "KPF-ONI-0826-B", verification: { status: "Demo verified", reference: "FPO-DEMO-26033-02", copy: "Illustrative FPO onboarding record; production verification would use consented organisation documents and field validation." }, traceability: [{ farmerCode: "TN-108", harvestCluster: "Gobichettipalayam cluster", contributedKg: 360, grade: "A", harvestedOn: "23 Aug 2026" }, { farmerCode: "TN-131", harvestCluster: "Gobichettipalayam cluster", contributedKg: 310, grade: "A", harvestedOn: "23 Aug 2026" }, { farmerCode: "TN-155", harvestCluster: "Erode cluster", contributedKg: 310, grade: "A", harvestedOn: "22 Aug 2026" }], demandSignal: "Balanced", color: "onion", comparison: { buyerSavings: 16, farmerUpliftPercent: 46, directFarmerSharePercent: 73 }, aggregation: { totalKg: 980, distinctFarmers: 3 } },
    { id: "groundnut-shell", crop: "Groundnut in shell", variety: "Big, naturally dried", category: "Nuts & oilseeds", grade: "Local premium", availableKg: 420, minOrderKg: 15, fpo: "Hosur Farmgate Network", state: "Tamil Nadu", harvestWindow: "Lot sealed 24 Aug", price: { directBuyerPrice: 96, farmerDirectEarnings: 76, fpoServices: 5, logistics: 8, qualityAndPacking: 7, conventionalBuyerPrice: 128, farmerConventionalEarnings: 55 }, marketReference: { pricePerKg: 90, market: "Hosur Uzhavar Sandhai", state: "Tamil Nadu", observedOn: "26 Aug 2026", source: "AGMARKNET / data.gov.in, modal price" }, lotCode: "HFN-GRN-0826-C", verification: { status: "Demo verified", reference: "FPO-DEMO-26033-03", copy: "Illustrative FPO onboarding record; production verification would use consented organisation documents and field validation." }, traceability: [{ farmerCode: "TN-203", harvestCluster: "Denkanikottai cluster", contributedKg: 220, grade: "Premium", harvestedOn: "20 Aug 2026" }, { farmerCode: "TN-214", harvestCluster: "Denkanikottai cluster", contributedKg: 200, grade: "Premium", harvestedOn: "20 Aug 2026" }], demandSignal: "Plan ahead", color: "groundnut", comparison: { buyerSavings: 32, farmerUpliftPercent: 38, directFarmerSharePercent: 79 }, aggregation: { totalKg: 420, distinctFarmers: 2 } },
    { id: "common-paddy", crop: "Paddy (common)", variety: "1001, FAQ grade", category: "Staples", grade: "FAQ", availableKg: 2400, minOrderKg: 100, fpo: "Godavari Grain Circle", state: "Andhra Pradesh", harvestWindow: "Bulk lot, mill-ready", price: { directBuyerPrice: 27, farmerDirectEarnings: 23.5, fpoServices: 1.1, logistics: 1.4, qualityAndPacking: 1, conventionalBuyerPrice: 35, farmerConventionalEarnings: 18.5 }, marketReference: { pricePerKg: 23.79, market: "Sampara (Kakinada Rural) APMC", state: "Andhra Pradesh", observedOn: "26 Aug 2026", source: "AGMARKNET / data.gov.in, modal price" }, lotCode: "GGC-PAD-0826-A", verification: { status: "Demo verified", reference: "FPO-DEMO-26033-04", copy: "Illustrative FPO onboarding record; production verification would use consented organisation documents and field validation." }, traceability: [{ farmerCode: "AP-031", harvestCluster: "Kakinada Rural cluster", contributedKg: 800, grade: "FAQ", harvestedOn: "21 Aug 2026" }, { farmerCode: "AP-052", harvestCluster: "Kakinada Rural cluster", contributedKg: 760, grade: "FAQ", harvestedOn: "21 Aug 2026" }, { farmerCode: "AP-074", harvestCluster: "Sampara cluster", contributedKg: 840, grade: "FAQ", harvestedOn: "22 Aug 2026" }], demandSignal: "Balanced", color: "paddy", comparison: { buyerSavings: 8, farmerUpliftPercent: 27, directFarmerSharePercent: 87 }, aggregation: { totalKg: 2400, distinctFarmers: 3 } },
  ],
  demand: [
    { crop: "Sun-ripened tomato", forecastKg: 742, recommendedKg: 683, plannedSupplyKg: 760, surplusKg: 18, risk: "Balanced", confidence: 82, explanation: "Recent direct orders and a confirmed bulk commitment are rising while reference arrivals are lower. List the first 680 kg now; retain the remainder for the next delivery wave." },
    { crop: "Red onion", forecastKg: 634, recommendedKg: 583, plannedSupplyKg: 980, surplusKg: 346, risk: "Watch", confidence: 74, explanation: "Committed demand supports the current lot, but reference arrivals are improving. Release in two clusters to limit price and holding risk." },
    { crop: "Groundnut in shell", forecastKg: 360, recommendedKg: 330, plannedSupplyKg: 420, surplusKg: 60, risk: "Balanced", confidence: 71, explanation: "Stable pantry demand and a longer shelf-life make this a suitable bulk-buyer lot; retain a 60 kg quality buffer." },
  ],
  logistics: { planCode: "SOUTH-CHN-07", status: "Ready to dispatch", cluster: "South Chennai: 1 bulk buyer + 4 family orders", vehicle: "Electric LCV · 1.2 tonne capacity", utilizationPercent: 82, plannedLoadKg: 984, routeComparison: { baselineKm: 86, optimizedKm: 54, kmSaved: 32, costSaved: 860, emissionsSavedKg: 9, routeEfficiencyPercent: 37 }, stops: [{ order: 1, name: "FPO consolidation hub", detail: "Shoolagiri · 06:30", kind: "origin" }, { order: 2, name: "Green Bowl Kitchens", detail: "Adyar · 10:05 · bulk", kind: "bulk" }, { order: 3, name: "Family order cluster", detail: "Besant Nagar · 10:28", kind: "consumer" }, { order: 4, name: "Family order cluster", detail: "Thiruvanmiyur · 10:47", kind: "consumer" }, { order: 5, name: "Family order cluster", detail: "Velachery · 11:12", kind: "consumer" }] },
  impact: { fulfilledOrders: 47, farmerIncomeUpliftPercent: 34, buyerSavingsInr: 14680, wasteAvoidedKg: 186, routeKmAvoided: 312, emissionsAvoidedKg: 75, directTradeValueInr: 82940, onTimeDeliveryPercent: 96 },
};
